ALTER TABLE BOOKINGS
ALTER COLUMN TOTAL_PRICE DECIMAL(10, 2);

INSERT INTO BOOKINGS(ROOM_ID, USER_ID, CHECK_IN_DATE, CHECK_OUT_DATE, TOTAL_PRICE)
VALUES 
(35, 2, GETDATE(), (GETDATE() + 6), dbo.FN_CALCULATE_AMOUNT(GETDATE(), (GETDATE() + 6), (SELECT PRICE_PER_NIGHT FROM ROOMS WHERE ID = 35))),
(42, 5, GETDATE(), (GETDATE() + 4), dbo.FN_CALCULATE_AMOUNT(GETDATE(), (GETDATE() + 4), (SELECT PRICE_PER_NIGHT FROM ROOMS WHERE ID = 42))),
(60, 8, GETDATE(), (GETDATE() + 7), dbo.FN_CALCULATE_AMOUNT(GETDATE(), (GETDATE() + 7), (SELECT PRICE_PER_NIGHT FROM ROOMS WHERE ID = 60))),
(22, 1, GETDATE(), (GETDATE() + 3), dbo.FN_CALCULATE_AMOUNT(GETDATE(), (GETDATE() + 3), (SELECT PRICE_PER_NIGHT FROM ROOMS WHERE ID = 22))),
(85, 16, GETDATE(), (GETDATE() + 9), dbo.FN_CALCULATE_AMOUNT(GETDATE(), (GETDATE() + 9), (SELECT PRICE_PER_NIGHT FROM ROOMS WHERE ID = 85)));

INSERT INTO BOOKINGS(ROOM_ID, USER_ID, CHECK_IN_DATE, CHECK_OUT_DATE, TOTAL_PRICE)
VALUES 
(50, 3, GETDATE(), (GETDATE() + 8), dbo.FN_CALCULATE_AMOUNT(GETDATE(), (GETDATE() + 8), (SELECT PRICE_PER_NIGHT FROM ROOMS WHERE ID = 50))),
(73, 7, GETDATE(), (GETDATE() + 6), dbo.FN_CALCULATE_AMOUNT(GETDATE(), (GETDATE() + 6), (SELECT PRICE_PER_NIGHT FROM ROOMS WHERE ID = 73))),
(99, 10, GETDATE(), (GETDATE() + 5), dbo.FN_CALCULATE_AMOUNT(GETDATE(), (GETDATE() + 5), (SELECT PRICE_PER_NIGHT FROM ROOMS WHERE ID = 99))),
(28, 4, GETDATE(), (GETDATE() + 2), dbo.FN_CALCULATE_AMOUNT(GETDATE(), (GETDATE() + 2), (SELECT PRICE_PER_NIGHT FROM ROOMS WHERE ID = 28))),
(112, 15, GETDATE(), (GETDATE() + 7), dbo.FN_CALCULATE_AMOUNT(GETDATE(), (GETDATE() + 7), (SELECT PRICE_PER_NIGHT FROM ROOMS WHERE ID = 112)));

INSERT INTO BOOKINGS(ROOM_ID, USER_ID, CHECK_IN_DATE, CHECK_OUT_DATE, TOTAL_PRICE)
VALUES 
(37, 9, GETDATE(), (GETDATE() + 10), dbo.FN_CALCULATE_AMOUNT(GETDATE(), (GETDATE() + 10), (SELECT PRICE_PER_NIGHT FROM ROOMS WHERE ID = 37))),
(41, 2, GETDATE(), (GETDATE() + 5), dbo.FN_CALCULATE_AMOUNT(GETDATE(), (GETDATE() + 5), (SELECT PRICE_PER_NIGHT FROM ROOMS WHERE ID = 41))),
(56, 12, GETDATE(), (GETDATE() + 6), dbo.FN_CALCULATE_AMOUNT(GETDATE(), (GETDATE() + 6), (SELECT PRICE_PER_NIGHT FROM ROOMS WHERE ID = 56))),
(63, 14, GETDATE(), (GETDATE() + 4), dbo.FN_CALCULATE_AMOUNT(GETDATE(), (GETDATE() + 4), (SELECT PRICE_PER_NIGHT FROM ROOMS WHERE ID = 63))),
(89, 13, GETDATE(), (GETDATE() + 8), dbo.FN_CALCULATE_AMOUNT(GETDATE(), (GETDATE() + 8), (SELECT PRICE_PER_NIGHT FROM ROOMS WHERE ID = 89)));

INSERT INTO BOOKINGS(ROOM_ID, USER_ID, CHECK_IN_DATE, CHECK_OUT_DATE, TOTAL_PRICE)
VALUES 
(11, 6, GETDATE(), (GETDATE() + 3), dbo.FN_CALCULATE_AMOUNT(GETDATE(), (GETDATE() + 3), (SELECT PRICE_PER_NIGHT FROM ROOMS WHERE ID = 11))),
(90, 19, GETDATE(), (GETDATE() + 9), dbo.FN_CALCULATE_AMOUNT(GETDATE(), (GETDATE() + 9), (SELECT PRICE_PER_NIGHT FROM ROOMS WHERE ID = 90))),
(82, 4, GETDATE(), (GETDATE() + 6), dbo.FN_CALCULATE_AMOUNT(GETDATE(), (GETDATE() + 6), (SELECT PRICE_PER_NIGHT FROM ROOMS WHERE ID = 82))),
(44, 5, GETDATE(), (GETDATE() + 7), dbo.FN_CALCULATE_AMOUNT(GETDATE(), (GETDATE() + 7), (SELECT PRICE_PER_NIGHT FROM ROOMS WHERE ID = 44))),
(66, 8, GETDATE(), (GETDATE() + 2), dbo.FN_CALCULATE_AMOUNT(GETDATE(), (GETDATE() + 2), (SELECT PRICE_PER_NIGHT FROM ROOMS WHERE ID = 66)));