USE BOOKING;

INSERT INTO REVIEWS(HOTEL_ID, USER_ID, RATING, REVIEW_TEXT)
VALUES
(1, 3, 7, 'Good hotel, but the service could be better.'),
(2, 5, 9, 'Amazing experience! Will definitely come back.'),
(3, 12, 6, 'Decent stay, but the room was a bit noisy.'),
(4, 7, 8, 'The room was clean and comfortable, but the location is a bit far.'),
(5, 9, 10, 'Perfect! Everything was exceptional.'),
(6, 1, 4, 'The hotel was fine, but there were a lot of issues with the heating system.'),
(7, 15, 8, 'Great value for the price, but could improve the food quality.'),
(8, 18, 6, 'Not bad, but there were a few issues with the bathroom.'),
(9, 10, 3, 'Very disappointing experience. The room was dirty and the staff was rude.'),
(10, 6, 7, 'Nice hotel, good location, but the amenities could be better.'),
(11, 8, 5, 'Okay stay, but the Wi-Fi was slow and unreliable.'),
(12, 14, 9, 'I loved it here! Staff were friendly and the room was perfect.'),
(13, 2, 7, 'The hotel was fine, but the elevator was slow.'),
(14, 13, 6, 'Overall okay, but the breakfast options were limited.'),
(15, 4, 8, 'Great stay, but I wish the gym had more equipment.'),
(16, 11, 9, 'Had a great time! Would recommend to friends.'),
(17, 16, 5, 'Good place, but I had trouble with the check-in process.'),
(18, 17, 8, 'Nice place to stay. Would come again next time I’m in town.'),
(19, 19, 10, 'Best hotel I’ve ever stayed at! Highly recommended.'),
(20, 3, 4, 'Hotel was okay, but noisy surroundings kept me awake.'),
(21, 5, 8, 'Comfortable stay, great amenities, but a bit pricy.'),
(22, 12, 9, 'Wonderful experience. The pool and view were incredible.'),
(23, 7, 3, 'Not worth the price. The room had several issues.'),
(24, 9, 6, 'It was decent, but I expected more based on the reviews.'),
(25, 10, 10, 'A great stay! Staff was friendly and helpful. Highly recommend.'),
(26, 4, 5, 'Okay for a short stay, but not for longer visits.'),
(27, 1, 7, 'Nice hotel, good location, but a little outdated.'),
(28, 15, 8, 'Great experience overall, though the food could use some variety.'),
(29, 18, 6, 'The room was fine, but I had issues with the air conditioning.'),
(30, 6, 9, 'Amazing stay! The hotel was perfect in every way.'),
(31, 8, 4, 'Room was fine, but had issues with cleanliness.'),
(32, 13, 7, 'Good value for the price, but a bit noisy at night.'),
(33, 2, 10, 'Loved everything! Will definitely come back here again.'),
(34, 14, 6, 'The hotel was good, but the amenities were a bit lacking.'),
(35, 11, 8, 'Great experience, but I wish the pool was open longer.'),
(36, 17, 5, 'Good hotel but had trouble with the hot water in the shower.'),
(37, 19, 7, 'Overall decent, but not outstanding.'),
(38, 3, 9, 'Fantastic stay. I enjoyed every moment here.'),
(39, 5, 6, 'Pretty good, but there were issues with the Wi-Fi connection.'),
(40, 12, 8, 'Great room and services, but the location could be better.'),
(41, 7, 3, 'The bathroom wasn’t cleaned well, and the staff were unhelpful.'),
(42, 9, 10, 'Everything was perfect! Loved my stay here.'),
(43, 10, 7, 'Comfortable stay, but the bed was a little too hard for me.'),
(44, 4, 6, 'Decent, but I had issues with the bathroom.'),
(45, 1, 9, 'Great stay, wonderful staff, and beautiful surroundings.'),
(46, 15, 5, 'Fine for a night or two, but I wouldn’t stay longer.'),
(47, 18, 6, 'Good hotel, but it was a bit noisy at night.'),
(48, 6, 8, 'Really nice experience, clean rooms and friendly staff.'),
(1, 4, 7, 'Decent value for the price.'),
(2, 13, 8, 'Would stay here again, but needs better breakfast options.'),
(3, 16, 6, 'The room was decent, but the hotel could improve its services.'),
(4, 9, 5, 'Okay stay, but not what I expected.'),
(5, 11, 10, 'Unbelievable experience! Everything exceeded my expectations.'),
(6, 2, 4, 'There were a lot of issues with the cleanliness.'),
(7, 8, 7, 'Nice stay, but the staff could be more helpful.'),
(8, 19, 6, 'The room was fine, but I had trouble with the air conditioning.'),
(9, 5, 8, 'Good value, great location, and friendly staff.'),
(10, 12, 9, 'An excellent experience overall.'),
(11, 1, 4, 'The heating was not working properly.'),
(12, 6, 7, 'Good hotel but noisy at night.'),
(13, 13, 6, 'Nice hotel, but the beds weren’t as comfortable as expected.'),
(14, 18, 5, 'Decent, but there were a few issues with the cleanliness.'),
(15, 7, 8, 'Good experience overall, but a little expensive for what you get.'),
(16, 3, 10, 'Absolutely perfect! I loved everything about this place.'),
(17, 10, 7, 'It was okay, but could have been better for the price.'),
(18, 11, 9, 'Great stay, I was impressed with the service.'),
(19, 15, 6, 'Not bad, but there were some things that need improvement.'),
(20, 13, 8, 'Very nice hotel with a great location.'),
(21, 17, 7, 'Had a good stay, but the room wasn’t as clean as I’d hoped.'),
(22, 6, 5, 'Okay, but not the best value for the money.'),
(23, 9, 8, 'Good hotel, but the breakfast could have been better.'),
(24, 1, 6, 'It was okay, but I had issues with the Wi-Fi.'),
(25, 2, 9, 'Wonderful stay, the staff were great!'),
(26, 14, 10, 'Exceeded my expectations! Everything was perfect.'),
(27, 8, 6, 'Good hotel, but the room was a little smaller than expected.'),
(28, 18, 5, 'Decent hotel, but needs some improvements in cleanliness.'),
(29, 10, 8, 'Nice stay, great staff, would come back again.'),
(30, 11, 7, 'Good hotel, though the bathroom could use some updating.'),
(31, 4, 6, 'Overall decent, but I expected a bit more.'),
(32, 19, 9, 'Fantastic experience. Loved everything.'),
(33, 13, 8, 'Would stay here again, but breakfast could use some work.'),
(34, 7, 7, 'Nice place, good service, but could improve the room decor.'),
(35, 8, 10, 'Everything was perfect.'),
(36, 16, 5, 'Okay experience, but the room wasn’t great.'),
(37, 14, 7, 'It was decent, but I think it could have been cleaner.'),
(38, 9, 8, 'Nice location, but could improve the amenities.'),
(39, 5, 10, 'Amazing stay! Highly recommend it.'),
(40, 12, 9, 'Really enjoyed my stay. Very satisfied.'),
(41, 7, 4, 'Room cleanliness was an issue for me.'),
(42, 6, 8, 'Great hotel, though the breakfast options were limited.'),
(43, 2, 6, 'Overall, it was okay, but could be better for the price.'),
(44, 10, 5, 'Decent hotel, but the air conditioning wasn’t working well.'),
(45, 3, 9, 'Really nice hotel, the staff were helpful and friendly.'),
(46, 13, 7, 'Good location, but the hotel could use some updates.'),
(47, 18, 8, 'I enjoyed my stay.'),
(48, 15, 6, 'Good location, but the room wasn’t as clean as I expected.');
