USE BOOKING;

INSERT INTO HOTELS (NAME, ADDRESS, CITY, COUNTRY, DESCRIPTION)
VALUES
    ('Hotel Sunshine', '123 Beach Rd', 'Miami', 'USA', 'A beachfront hotel offering luxurious amenities and stunning ocean views.'),
    ('Mountain Resort', '456 Hilltop Ave', 'Denver', 'USA', 'A cozy resort nestled in the Rocky Mountains, perfect for hiking and skiing.'),
    ('City Palace Hotel', '789 Downtown Blvd', 'New York', 'USA', 'A luxurious hotel located in the heart of New York City, offering upscale rooms and dining.'),
    ('Grand Canyon Lodge', '10 Canyon Dr', 'Grand Canyon', 'USA', 'An iconic lodge with breathtaking views of the Grand Canyon, ideal for nature lovers.'),
    ('Lakeside Retreat', '250 Lakeview St', 'Seattle', 'USA', 'A tranquil retreat by a beautiful lake, offering outdoor activities and relaxation.'),
    ('Desert Oasis Hotel', '123 Dune Rd', 'Las Vegas', 'USA', 'A luxurious desert hotel with a glamorous casino and world-class entertainment.'),
    ('Snowy Mountain Inn', '300 Alpine Rd', 'Aspen', 'USA', 'A luxurious winter getaway with top-tier skiing and après-ski experiences.'),
    ('Royal Orchid Hotel', '4 Orchid St', 'Bangkok', 'Thailand', 'A tropical escape with a beautiful garden, stunning views, and Thai-inspired decor.'),
    ('Siam Square Resort', '202 Siam Square', 'Bangkok', 'Thailand', 'A vibrant hotel near the heart of Bangkok’s shopping and entertainment district.'),
    ('Beachfront Paradise', '45 Coconut Blvd', 'Phuket', 'Thailand', 'A tropical beachfront resort offering water sports, dining, and relaxing spa treatments.'),
    ('Jungle Retreat', '678 Rainforest Rd', 'Chiang Mai', 'Thailand', 'A peaceful eco-resort surrounded by lush greenery and close to Chiang Mai’s wildlife parks.'),
    ('Luxury Waterfront Hotel', '101 Ocean Ave', 'Sydney', 'Australia', 'A luxury hotel located by the Sydney Harbour, offering stunning views of the Opera House.'),
    ('Outback Lodge', '50 Red Desert Rd', 'Alice Springs', 'Australia', 'An adventure-focused lodge offering access to the vast Australian Outback.'),
    ('Beachside Bungalows', '300 Coral Rd', 'Gold Coast', 'Australia', 'Charming bungalows right on the beach with a variety of water activities.'),
    ('Urban Retreat', '123 City Center Blvd', 'Melbourne', 'Australia', 'A modern hotel with contemporary amenities, perfect for city exploration.'),
    ('Hotel Pacific', '202 Oceanfront Ave', 'Auckland', 'New Zealand', 'A scenic beachfront hotel offering stunning views and water activities.'),
    ('Wellington Boutique Hotel', '450 Lambton Quay', 'Wellington', 'New Zealand', 'A boutique hotel with a cozy atmosphere and easy access to the city’s cultural attractions.'),
    ('Coromandel Lodge', '60 Seaside Rd', 'Coromandel', 'New Zealand', 'A charming lodge surrounded by the natural beauty of Coromandel Peninsula.'),
    ('Sunset Resort', '100 Sunset Blvd', 'Bora Bora', 'French Polynesia', 'A luxury resort on a private island offering overwater bungalows and crystal-clear waters.'),
    ('Tahiti Paradise', '150 Ocean Rd', 'Papeete', 'French Polynesia', 'An exclusive resort on the shores of Tahiti with world-class spa services and breathtaking views.'),
    ('Luxury Safari Lodge', '200 Savanna Rd', 'Masai Mara', 'Kenya', 'A premium lodge offering luxurious accommodations with the best safari experiences.'),
    ('Lake Victoria Hotel', '500 Lakeside St', 'Kisumu', 'Kenya', 'A lakeside hotel offering stunning views and fresh water activities on Lake Victoria.'),
    ('Desert Mirage Hotel', '75 Oasis Blvd', 'Dubai', 'UAE', 'A luxurious desert hotel featuring a world-class spa, pool, and fine dining.'),
    ('Burj View Hotel', '10 Sheikh Zayed Rd', 'Dubai', 'UAE', 'A 5-star hotel with views of the iconic Burj Khalifa and luxurious shopping experiences.'),
    ('Grand Alhambra Hotel', '150 Alhambra Ave', 'Dubai', 'UAE', 'A lavish hotel with Arabic-inspired architecture and a range of high-end facilities.'),
    ('Mount Kilimanjaro Lodge', '350 Trekker Rd', 'Moshi', 'Tanzania', 'A serene lodge with views of Mount Kilimanjaro, ideal for hiking and relaxation.'),
    ('Serengeti Camp', '200 Wildlife Rd', 'Serengeti', 'Tanzania', 'A luxury tented camp offering exclusive safari tours in the Serengeti National Park.'),
    ('Imperial Palace Hotel', '23 Imperial Ave', 'Beijing', 'China', 'A grand hotel featuring ancient Chinese architecture and cultural experiences.'),
    ('Great Wall Resort', '100 Wall Rd', 'Beijing', 'China', 'A luxurious hotel offering stunning views of the Great Wall of China, ideal for cultural exploration.'),
    ('Shanghai Skyline Hotel', '456 Lujiazui Rd', 'Shanghai', 'China', 'A modern hotel located in the city’s financial district, offering panoramic city views.'),
    ('Bali Beach Resort', '33 Coconut Grove', 'Denpasar', 'Indonesia', 'A tropical beachfront resort offering relaxation, water sports, and luxurious accommodations.'),
    ('Ubud Jungle Lodge', '12 Monkey Forest Rd', 'Ubud', 'Indonesia', 'A peaceful lodge surrounded by lush jungle, offering yoga, meditation, and spa services.'),
    ('Mount Rinjani Lodge', '250 Volcano Rd', 'Lombok', 'Indonesia', 'A scenic lodge offering hiking tours and breathtaking views of Mount Rinjani.'),
    ('Andaman Resort', '8 Andaman Ave', 'Phuket', 'Thailand', 'A beachfront resort with luxury suites and exceptional diving experiences.'),
    ('Hotel Marigot', '1 Marigot Bay', 'Castries', 'Saint Lucia', 'A luxury resort offering stunning views of Marigot Bay and top-tier relaxation services.'),
    ('St. Lucia Eco Retreat', '500 Rainforest Rd', 'Soufriere', 'Saint Lucia', 'A serene retreat offering eco-friendly accommodations in the heart of Saint Lucia’s natural beauty.'),
    ('Grand Hyatt Tokyo', '10 Roppongi Hills', 'Tokyo', 'Japan', 'A luxury hotel located in the heart of Tokyo’s Roppongi district, offering modern amenities and fine dining.'),
    ('Kyoto Zen Hotel', '200 Kiyomizu Rd', 'Kyoto', 'Japan', 'A traditional hotel offering Zen-inspired rooms and proximity to Kyoto’s famous temples.'),
    ('Fushimi Inari Lodge', '75 Torii Rd', 'Kyoto', 'Japan', 'A peaceful retreat near Fushimi Inari Shrine, offering Japanese tea ceremonies and cultural experiences.'),
    ('Parisian Retreat', '5 Champs-Élysées', 'Paris', 'France', 'A stylish boutique hotel offering a Parisian experience with access to cultural landmarks.'),
    ('Eiffel View Hotel', '15 Rue de Montmartre', 'Paris', 'France', 'A luxury hotel with an iconic view of the Eiffel Tower and world-class dining options.'),
    ('Normandy Beach Hotel', '200 Normandy Rd', 'Nice', 'France', 'A seaside hotel offering breathtaking views of the Mediterranean and luxurious beach access.'),
    ('Swiss Alps Lodge', '50 Alpine Rd', 'Zurich', 'Switzerland', 'A cozy lodge located in the Swiss Alps, perfect for skiing and outdoor adventures.'),
    ('Geneva Lakeside Hotel', '300 Lake Geneva Rd', 'Geneva', 'Switzerland', 'A lakeside hotel offering picturesque views of Lake Geneva and elegant Swiss cuisine.'),
    ('Swiss Retreat', '100 Mountain View Ave', 'Lucerne', 'Switzerland', 'A peaceful retreat surrounded by the scenic beauty of Lucerne’s mountains and lakes.'),
    ('Italian Villa Resort', '100 Tuscany Rd', 'Florence', 'Italy', 'A luxurious villa offering wine tours, cooking classes, and access to Tuscany’s countryside.'),
    ('Rome Grand Hotel', '50 Via del Corso', 'Rome', 'Italy', 'A historical hotel located near the Roman Forum, ideal for exploring ancient landmarks.'),
    ('Venetian Palazzo', '150 Grand Canal Rd', 'Venice', 'Italy', 'A majestic hotel along the Grand Canal offering gondola rides and gourmet dining.');
